import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f9faf5',
        surface: '#f9faf5',
        'surface-dim': '#d9dad6',
        'surface-bright': '#f9faf5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f0',
        'surface-container': '#edeeea',
        'surface-container-high': '#e8e8e4',
        'surface-container-highest': '#e2e3df',
        'surface-variant': '#e2e3df',
        'on-surface': '#1a1c1a',
        'on-surface-variant': '#45474d',
        'inverse-surface': '#2f312e',
        'inverse-on-surface': '#f0f1ed',
        primary: '#051125',
        'primary-container': '#1b263b',
        'on-primary': '#ffffff',
        'on-primary-container': '#828da7',
        'primary-fixed': '#d7e2ff',
        'primary-fixed-dim': '#bbc6e2',
        'on-primary-fixed': '#101b30',
        'on-primary-fixed-variant': '#3c475d',
        'inverse-primary': '#bbc6e2',
        secondary: '#47607e',
        'secondary-container': '#c2dcff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#48617e',
        'secondary-fixed': '#d1e4ff',
        'secondary-fixed-dim': '#afc9ea',
        'on-secondary-fixed': '#001d36',
        'on-secondary-fixed-variant': '#2f4865',
        tertiary: '#001225',
        'tertiary-container': '#0f273f',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#798fab',
        'tertiary-fixed': '#d1e4ff',
        'tertiary-fixed-dim': '#b2c8e7',
        'on-tertiary-fixed': '#031d34',
        'on-tertiary-fixed-variant': '#334861',
        outline: '#75777d',
        'outline-variant': '#c5c6cd',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface-tint': '#545e76',
        'on-background': '#1a1c1a',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'max-width': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['Inter'],
        'headline-sm': ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'label-md': ['Inter'],
        'label-sm': ['Inter'],
        'display-lg': ['Inter'],
        'display-lg-mobile': ['Inter'],
      },
      maxWidth: {
        app: '1280px',
      },
    },
  },
  plugins: [],
};

export default config;
